# Stubs for pycroft.model (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def create_db_model(bind: Any) -> None: ...
def drop_db_model(bind: Any) -> None: ...
